server:
  port: 8080

spring:
  application:
    name: arogya-flow-backend

  jackson:
    time-zone: Asia/Kolkata

  datasource:
    url: jdbc:postgresql://localhost:5432/arogyaflow
    username: postgres
    password: "#@Ditya06"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Kolkata
  mail:
    host: smtp.gmail.com
    port: 587
    username: mishraaditya6001@gmail.com
    password: <YOUR_APP_PASSWORD>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
